kookmin-sw/2018-cap1-4

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/drools/DroolsSpringTest.java
- src/main/java/com/company/dto/DomainRuleVO.java
- src/main/java/com/company/dto/MedicineVO.java
- src/main/java/com/company/dto/MemberVO.java
- src/main/java/com/company/dto/PatientDiagnosisVO.java
- src/main/java/com/company/dto/PatientVO.java
- src/main/java/com/company/dto/PrescriptionGroupVO.java
- src/main/java/com/company/dto/PrescriptionVO.java
- src/main/java/com/company/dto/SymptomVO.java
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/WEB-INF/views/generalSurvey.jsp
- src/main/webapp/WEB-INF/views/hospitalSurvey.jsp
- src/main/webapp/WEB-INF/views/login.jsp
- src/main/webapp/WEB-INF/views/receptionPage.jsp
접수 추가 후 탭 간 연동 완료 했습니다. 확인바랍니다.
> 접수 메뉴 추가 및 설문지, 로그인 jsp 추가

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/dto/DoctorVO.java
- src/main/java/com/company/dto/MemberVO.java
- src/main/java/com/company/interceptor/LoginInterceptor.java
- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/WEB-INF/views/evalTablePage.jsp
- src/main/webapp/WEB-INF/views/home.jsp
- src/main/webapp/WEB-INF/views/receptionPage.jsp
수정 내용
/mybatis 의 첫 url을 /home 으로 수정
처음 초기화면에 의사 버튼만 현재 맵핑 되어 있고 의사 버튼 클릭시 로그인 화면으로 이동
현재 로그인 아이디는 id : admin // pw :123 으로 임시 저장 로그인 확인 되면 의사 페이지로 이동
@jjcec 는 코드 수정후 빌드하고 localhost:8080/home/defaultPage 로 결과를 확인하시면 됩니다.
현재 인터셉트는 개발 편의를 위해서 주석처리 하였습니다.
> home 화면부터인터셉터를 이용한 로그인 체크

- src/main/webapp/WEB-INF/views/hospitalSurvey.jsp
병원에서 사용할 설문조사를
기존에 있던 설문조사 자료를 기반으로 만들었습니다.
> fill hospitalSurvey.jsp UI

- src/main/java/com/company/controller/HomeController.java
평가 탭 컨트롤러 맵핑을 누락시켜서 다시 추가 하여 올립니다.
> add evalRule controller mapping

- src/main/webapp/WEB-INF/views/receptionPage.jsp
> made basic receptionPage UI

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/controller/MemberController.java
- src/main/java/com/company/mapper/MemberMapper.java
- src/main/java/com/company/mapper/MemberMapper.xml
- src/main/java/com/company/service/MemberService.java
- src/main/java/com/company/service/impl/MemberServiceImpl.java
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/WEB-INF/views/evalTablePage.jsp
- src/main/webapp/WEB-INF/views/home.jsp
- src/main/webapp/WEB-INF/views/receptionPage.jsp
- src/main/webapp/js/search.js
기본적인 검색을 하기위해서 mybatis를 이용한 mapper 
추가 하였습니다.
> mapper setting

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/dto/DoctorVO.java
- src/main/java/com/company/interceptor/LoginInterceptor.java
- src/main/java/com/company/mapper/LoginMapper.java
- src/main/java/com/company/mapper/LoginMapper.xml
- src/main/java/com/company/service/LoginService.java
- src/main/java/com/company/service/impl/LoginServiceImpl.java
- src/main/webapp/WEB-INF/db.properties
- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- src/main/webapp/WEB-INF/views/login.jsp
cookie를 이용하여 id 를 로컬에서 기억을 해두고 보안에 중요한 session 정보는 서버에 저장을 하게 
설정하였습니다.
현재는 개발 편의를 위해서 인터셉터를 설정을 해제해 두어서 올립니다.
> add login using cookie and session to remember id

- src/main/webapp/WEB-INF/views/defaultPage.jsp
기존에 전체적으로 잡혀있지 않았던 틀을 수정했고 사진이 뜨지 않는 오류를 수정했습니다.
> systemized UI

- src/main/webapp/WEB-INF/views/generalSurvey.jsp
2단계 사상체질 설문을 위한 
기본 판단 (음인/양인) 설문 입니다.
> 사상체질 설문 초안 작성

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/dto/DoctorVO.java
- src/main/webapp/WEB-INF/views/home.jsp
- src/main/webapp/WEB-INF/web.xml
톰캣 서버간 세션 클러스터링을 위한 환경설정을 하였습니다.
wem.xml 부분을 추가하였고 세션을 유지하는 attribute는 객체 직렬화를 해야하기 때문에
`public class DoctorVO implements Serializable` 이런식으로 구성하였습니다.
Tomcat Server config 파일 설정을 따로 하여야 하는데
이 방법은 issue에 올려놓겠습니다.
> ready to WAS Session Clustering

- src/main/java/com/company/controller/RuleController.java
- src/main/java/com/company/mapper/RuleMapper.java
- src/main/java/com/company/mapper/RuleMapper.xml
- src/main/java/com/company/service/RuleService.java
- src/main/java/com/company/service/impl/RuleServiceImpl.java
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/js/diagnosis.js
증상 목록이 있는 DB 테이블에서 증상을 검색했을때 자동완성 기능을 통해서
검색이 되도록 구현
> add searching symptom through search input

- src/main/webapp/WEB-INF/views/receptionPage.jsp
> first link hospitalSurvey from receptionPage

- src/main/java/com/company/controller/RuleController.java
- src/main/java/com/company/drools/DroolsSpringTest.java
- src/main/java/com/company/mapper/RuleMapper.java
- src/main/java/com/company/mapper/RuleMapper.xml
- src/main/java/com/company/po/RuleMap.java
- src/main/java/com/company/service/RuleService.java
- src/main/java/com/company/service/impl/RuleServiceImpl.java
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/WEB-INF/views/login.jsp
- src/main/webapp/js/diagnosis.js
drools 엔진으로 진단하기 위한 Ajax 를 이용한 컨트롤러 연동을 하였습니다.
> set drools bean object

- src/main/java/com/company/controller/RuleController.java
- src/main/java/com/company/po/RuleMap.java
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/WEB-INF/views/receptionPage.jsp
- src/main/webapp/js/diagnosis.js
진단하기 버튼 수정완료 survey랑 연동하시면 됩니다.
> modify diagnosis button

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/controller/RuleController.java
- src/main/java/com/company/drools/DroolsSpringTest.java
- src/main/resources/rules/rules.drl
- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/WEB-INF/views/login.jsp
- src/main/webapp/WEB-INF/views/receptionPage.jsp
> add test rule

- doc/태양소양.html
- doc/태음소음.html
> 사상체질 설문 수정

- src/main/java/com/company/controller/RuleController.java
- src/main/java/com/company/drools/DroolsSpringTest.java
- src/main/java/com/company/dto/PatientSymptomVO.java
- src/main/java/com/company/dto/PatientVO.java
- src/main/java/com/company/po/RuleMap.java
- src/main/java/com/company/service/LoginService.java
- src/main/java/com/company/util/ApplicationContextProvider.java
- src/main/java/com/company/util/BeanUtils.java
- src/main/resources/drools-context/applicationContext-drools.xml
- src/main/webapp/WEB-INF/spring/applicationContext-dao.xml
- src/main/webapp/WEB-INF/views/defaultPage.jsp
효율적인 빈객체 관리를 위해서 스프링 컨테이너 빈객체 확인 패키지 및 클래스 생성했습니다.
> Fetch bean obj

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/controller/RuleController.java
- src/main/webapp/WEB-INF/views/home.jsp
기존 아래에 내려와있던 홈페이지 화면을 전체적으로 조정했습니다.
> modify homePage

- src/main/webapp/WEB-INF/views/generalSurvey.jsp
> modify generalSurvey

- src/main/java/com/company/controller/HomeController.java
- src/main/java/com/company/controller/MemberController.java
- src/main/java/com/company/controller/RuleController.java
- src/main/java/com/company/controller/SurveyController.java
- src/main/java/com/company/mapper/MemberMapper.java
- src/main/java/com/company/mapper/MemberMapper.xml
- src/main/java/com/company/service/MemberService.java
- src/main/java/com/company/service/impl/MemberServiceImpl.java
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/WEB-INF/views/evalTablePage.jsp
- src/main/webapp/WEB-INF/views/resultPage.jsp
- src/main/webapp/js/evalRule.js
- src/main/webapp/js/resultPage.js
평가 페이지 클릭시 데이터 베이스 불러오기 완료
ruleController 주석 풀고 머지 했습니다.
> when access evaluate tab, select data from databases

- src/main/java/com/company/controller/HomeController.java
- src/main/webapp/WEB-INF/views/generalSurvey.jsp
- src/main/webapp/WEB-INF/views/generalSurvey_B.jsp
- src/main/webapp/WEB-INF/views/generalSurvey_C.jsp
generalSurvey B,C UI랑 이전, 다음 버튼 디자인 변경했습니다.
> modify survey UI & button

- src/main/webapp/WEB-INF/views/hospitalSurvey.jsp
> modify hospitalSurvey UI

- src/main/resources/rules/rules.drl
> Mapping rules in drl file

- src/main/java/com/company/controller/MemberController.java
- src/main/webapp/WEB-INF/views/evalTablePage.jsp
- src/main/webapp/WEB-INF/views/receptionPage.jsp
- src/main/webapp/js/reception.js
> add funtion to refresh reception input page

- pom.xml
- src/main/java/com/company/controller/SurveyController.java
- src/main/java/com/company/dto/GeneralSurveyVO.java
- src/main/java/com/company/mapper/RuleMapper.java
- src/main/java/com/company/mapper/RuleMapper.xml
- src/main/java/com/company/service/RuleService.java
- src/main/java/com/company/service/impl/RuleServiceImpl.java
- src/main/webapp/WEB-INF/views/resultPage.jsp
설문지 작성 완료 했을때 컨트롤러는 해당 데이터베이스 값을 가져와 결과 페이지에 보여줍니다.
> connet general Result Page 

- src/main/java/com/company/controller/RuleController.java
- src/main/webapp/WEB-INF/views/hospitalResultPage.jsp
> made hospitalSurveyPage UI

- src/main/java/com/company/controller/RuleController.java
- src/main/java/com/company/controller/SurveyController.java
- src/main/webapp/WEB-INF/views/defaultPage.jsp
- src/main/webapp/js/resultPage.js
출력 버튼을 만들고 버튼을 클릭했을 때 결과 페이지 이동 기능 구현
> Print function

- src/main/webapp/WEB-INF/views/generalSurvey.jsp
> made input name box
